server:
  port: 8001
mybatis:
  type-aliases-package: com.wzc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: "000000"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/  #单机
      #(集群)defaultZone: http://7001.com,http://7002.com,http://7003.com
  instance:
    instance-id: springcloud-provider-dept-8001   #修改Eureka默认描述信息

info:
  app.name: SpringCloud
  company.name: SuNing
