server:
  port: 7001
eureka:
  instance:
    hostname: localhost   #Eureka服务端的实例的名字
  client:
    register-with-eureka: false   #是否像Eureka注册中心注册自己
    fetch-registry: false    #如果是false，表示自己为注册中心
    service-url:    #和Eureka监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机
      #defaultZone: http://7002.com,http://7003.com(集群)